--CREATE TABLE LEAVE_TYPE (ID INT IDENTITY(1,1), LEAVE_TYPE VARCHAR(200), SYS_DATE DATETIME)
INSERT INTO LEAVE_TYPE (LEAVE_TYPE,SYS_DATE)VALUES('BONUS LEAVE',GETDATE())

SELECT LEAVE_TYPE FROM LEAVE_TYPE

--CREATE TABLE DAY_SHIFT (ID INT IDENTITY(1,1), MODE VARCHAR(100), SYS_DATE DATETIME)
insert into DAY_SHIFT(MODE, SYS_DATE) values('FULL DAY', GETDATE())
--alter table day_shift add MODE_VALUE VARCHAR(100)
UPDATE DAY_SHIFT SET MODE_VALUE='9' WHERE MODE='FULL DAY' 
SELECT MODE,MODE_VALUE FROM DAY_SHIFT
SELECT *FROM SYS.TABLES
select * from leave_records
--CREATE TABLE LEAVE_RECORDS (ID INT IDENTITY (1,1),TXT_LEAVE_TYPE VARCHAR (100), TXT_SHIFT_TYPE VARCHAR (100) , HOLIDAY_OR_WORKING_HRS VARCHAR(100), LEAVE_COMMENT VARCHAR(1000), STARTDATE DATETIME, ENDDATE DATETIME, SYS_DATE DATETIME )
SELECT  LEAVEID, TXT_LEAVE_TYPE,TXT_SHIFT_TYPE,HOLIDAY_OR_WORKING_HRS,	STARTDATE,	ENDDATE,LEAVE_COMMENT  FROM LEAVE_RECORDS order by id desc
SELECT  LEAVEID, TXT_LEAVE_TYPE,TXT_SHIFT_TYPE,HOLIDAY_OR_WORKING_HRS,	STARTDATE,	ENDDATE,LEAVE_COMMENT  FROM LEAVE_RECORDS where LEAVEID='lev1043'

--alter table leave_Records add LEAVEID VARCHAR (100)

INSERT INTO LEAVE_RECORDS (TXT_LEAVE_TYPE,TXT_SHIFT_TYPE,HOLIDAY_OR_WORKING_HRS,LEAVE_COMMENT,STARTDATE,ENDDATE,SYS_DATE,LEAVEID) 
VALUES ('BONUS LEAVE','FULL DAY','1','hello bro','25-03-2024','25-03-2024','2024-03-23 23:10:48','LEV1039')

delete from LEAVE_RECORDS where LEAVEID='sdfd'

select leaveid from leave_records where leaveid='LEV1045'

truncate table leave_records
alter PROCEDURE PROC_GENLEAVEID
--@passvalue int output
as
begin
declare @retvalue int
set @retvalue =NEXT VALUE FOR SEQ_LEAVEID
--print @retvalue
--set @passvalue=@retvalue
return @retvalue
end
go

EXEC PROC_GENLEAVEID

CREATE SEQUENCE SEQ_LEAVEID
start with 1001
increment by 1
minvalue 1001
maxvalue 99999

SELECT  NEXT VALUE FOR SEQ_LEAVEID
--EXEC SEQ_LEAVEID gives an error


